# **OLIST BRAZILIAN E-COMMERCE SALES PERFORMANCE DATA CLEANING**

## **1. Load Data**

In [107]:
import pandas as pd
import numpy as np

# Fact tables
orders_raw = pd.read_csv("olist_orders_dataset.csv")
order_items_raw = pd.read_csv("olist_order_items_dataset.csv")
order_payments_raw = pd.read_csv("olist_order_payments_dataset.csv")
order_reviews_raw = pd.read_csv("olist_order_reviews_dataset.csv")

orders = orders_raw.copy()
order_items = order_items_raw.copy()
order_payments = order_payments_raw.copy()
order_reviews = order_reviews_raw.copy()

# Dimension tables
customers_raw = pd.read_csv("olist_customers_dataset.csv")
products_raw = pd.read_csv("olist_products_dataset.csv")
sellers_raw = pd.read_csv("olist_sellers_dataset.csv")
category_translation_raw = pd.read_csv("product_category_name_translation.csv", encoding="utf-8-sig")

customers = customers_raw.copy()
products = products_raw.copy()
sellers = sellers_raw.copy()
category_translation = category_translation_raw.copy()

## **2. Initial Data Inspection**

In [108]:
# INITIAL DATA INSPECTION

datasets = {
    "orders": orders,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "products": products,
    "customers": customers,
    "sellers": sellers,
    "category_translation": category_translation
}

for name, df in datasets.items():
    print(f"\n{'='*40}")
    print(f"{name} Table")
    print(f"{'='*40}")
    print("Shape:", df.shape)
    print("\nInfo:")
    df.info()
    print("\nPreview:")
    display(df.head())

========================================
orders Table
========================================
Shape: (99441, 8)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

Preview:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

========================================
order_items Table
========================================
Shape: (112650, 7)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

Preview:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

========================================
order_payments Table
========================================
Shape: (103886, 5)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

Preview:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

========================================
order_reviews Table
========================================
Shape: (99224, 7)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

Preview:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

========================================
products Table
========================================
Shape: (32951, 9)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

Preview:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

========================================
customers Table
========================================
Shape: (99441, 5)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

Preview:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

========================================
sellers Table
========================================
Shape: (3095, 4)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

Preview:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

========================================
category_translation Table
========================================
Shape: (71, 2)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

Preview:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

## **3. Converting Incorrect Data Type**

In [109]:
# CONVERT INCORRECT OBJECT TYPE INTO DATE TYPE

# Convert timestamps
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"], errors="coerce"
)
orders["order_approved_at"] = pd.to_datetime(
    orders["order_approved_at"], errors="coerce"
)
orders["order_delivered_carrier_date"] = pd.to_datetime(
    orders["order_delivered_carrier_date"], errors="coerce"
)
orders["order_delivered_customer_date"] = pd.to_datetime(
    orders["order_delivered_customer_date"], errors="coerce"
)
orders["order_estimated_delivery_date"] = pd.to_datetime(
    orders["order_estimated_delivery_date"], errors="coerce"
)
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"], errors="coerce"
)
order_reviews["review_creation_date"] = pd.to_datetime(
    order_reviews["review_creation_date"], errors="coerce"
)
order_reviews["review_answer_timestamp"] = pd.to_datetime(
    order_reviews["review_answer_timestamp"], errors="coerce"
)

# Keep only 2018 orders
orders = orders[
    (orders["order_purchase_timestamp"] >= "2018-01-01") &
    (orders["order_purchase_timestamp"] < "2019-01-01")]

## **4. Handling Missing Values**

In [110]:
# DOUBLE CHECK MISSING VALUES FOR ALL TABLES

datasets = {
    "orders": orders,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "products": products,
    "customers": customers,
    "sellers": sellers,
    "category_translation": category_translation
}

for name, df in datasets.items():
    print(f"\n{name} - Missing Values by Column:")
    print(df.isnull().sum())

orders - Missing Values by Column:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  82
order_delivered_carrier_date      591
order_delivered_customer_date    1233
order_estimated_delivery_date       0
dtype: int64

order_items - Missing Values by Column:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

order_payments - Missing Values by Column:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

order_reviews - Missing Values by Column:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

products - Missing Values by Column:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

customers - Missing Values by Column:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

sellers - Missing Values by Column:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

category_translation - Missing Values by Column:
product_category_name            0
product_category_name_english    0
dtype: int64

In [111]:
# DROP NULL VALUES

# Drop rows with nulls in products table
products = products.dropna(subset=[
    'product_id', 
    'product_category_name', 
    'product_name_lenght', 
    'product_description_lenght',
    'product_photos_qty',
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
])

products = products.reset_index(drop=True)

# Drop rows with nulls in orders table
orders = orders.dropna(subset=[
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date"
])

orders = orders.reset_index(drop=True)

In [112]:
# DROP COLUMNS WITH PREDOMINANTLY NULL VALUES

order_reviews = order_reviews.drop(columns=[
    "review_comment_title", 
    "review_comment_message"
])

In [113]:
# CHECK IF NULL VALUE STILL EXIST
datasets = {
    "orders": orders,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "products": products,
    "customers": customers,
    "sellers": sellers,
    "category_translation": category_translation
}

for name, df in datasets.items():
    print(f"Nulls in {name}:")
    print(df.isnull().sum())
    print("-"*50)

Nulls in orders:
order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64
--------------------------------------------------
Nulls in order_items:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
--------------------------------------------------
Nulls in order_payments:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
--------------------------------------------------
Nulls in order_reviews:
review_id                  0
order_id                   0
review_score               0
review_creation_date       0
review_answer_timestamp    0
dtype: int64
--------------------------------------------------
Nulls in products:
product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64
--------------------------------------------------
Nulls in customers:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
--------------------------------------------------
Nulls in sellers:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
--------------------------------------------------
Nulls in category_translation:
product_category_name            0
product_category_name_english    0
dtype: int64
--------------------------------------------------

## **5. Handling Duplicate Data**

In [114]:
# CHECK DUPLICATE DATA FOR ALL TABLES

datasets = {
    "orders": orders,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "products": products,
    "customers": customers,
    "sellers": sellers,
    "category_translation": category_translation
}

for name, df in datasets.items():
    duplicates = df.duplicated().sum()
    print(f"{name} - Number of duplicate rows: {duplicates}")

orders - Number of duplicate rows: 0
order_items - Number of duplicate rows: 0
order_payments - Number of duplicate rows: 0
order_reviews - Number of duplicate rows: 0
products - Number of duplicate rows: 0
customers - Number of duplicate rows: 0
sellers - Number of duplicate rows: 0
category_translation - Number of duplicate rows: 0

No duplicate entries were detected in the dataset, so no cleaning was necessary.

## **6. Handling Inconsistent Data**

In [115]:
# CHECK CATEGORICAL VALUE CONSISTENCY FOR ALL TABLES

datasets = {
    "orders": orders,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "products": products,
    "customers": customers,
    "sellers": sellers,
    "category_translation": category_translation
}

print("=== CATEGORICAL VALUE CONSISTENCY CHECK ===")
for name, df in datasets.items():
    cat_cols = df.select_dtypes(include="object").columns
    if len(cat_cols) == 0:
        print(f"\n{name}: No categorical columns")
        continue

    print(f"\n{name}:")
    for col in cat_cols:
        unique_values = df[col].str.strip().unique()
        print(f"  {col}: {unique_values}")

=== CATEGORICAL VALUE CONSISTENCY CHECK ===

orders:
  order_id: ['53cdb2fc8bc7dce0b6741e2150273451' '47770eb9100c2d0c44946d9cf07ec65d'
 'ad21c59c0840e6cb83a9ceb5573f8159' ... '63943bddc261676b46f01ca7ac2f7bd8'
 '11c177c8e97725db2631073c19f07b62' '66dea50a8b16d9b4dee7af250b4be1a5']
  customer_id: ['b0830fb4747a6c6d20dea0b8c802d7ef' '41ce2a54c0b03bf3443c3d931a367089'
 '8ab97904e6daea8866dbdbc4fb7aad2c' ... '1fca14ff2861355f6e5f14306ff977a7'
 'b331b74b18dc79bcdf6532d51e1637c1' 'edb027a75a1449115f6b43211ae02a24']
  order_status: ['delivered' 'canceled']

order_items:
  order_id: ['00010242fe8c5a6d1ba2dd792cb16214' '00018f77f2f0320c557190d7a144bdd3'
 '000229ec398224ef6ca0657da4fc703e' ... 'fffce4705a9662cd70adb13d4a31832d'
 'fffe18544ffabc95dfada21779c9644f' 'fffe41c64501cc87c801fd61db3f6244']
  product_id: ['4244733e06e7ecb4970a6e2683c13e61' 'e5f2d52b802189ee658865ca93d83a8f'
 'c777355d18b72b67abbeef9df44fd0fd' ... 'dd469c03ad67e201bc2179ef077dcd48'
 'bbe7651fef80287a816ead73f065fc4b' '350688d9dc1e75ff97be326363655e01']
  seller_id: ['48436dade18ac8b2bce089ec2a041202' 'dd7ddc04e1b6c2c614352b383efe2d36'
 '5b51032eddd242adc84c38acab88f23d' ... '3fefda3299e6dfaea3466ef346a3571a'
 '80ceebb4ee9b31afb6c6a916a574a1e2' '3e35a8bb43569389d3cebef0ce820f69']

order_payments:
  order_id: ['b81ef226f3fe1789b1e8b2acac839d17' 'a9810da82917af2d9aefd1278f1dcfa0'
 '25e8ea4e93396b6fa0d3dd708e76c1bd' ... '32609bbb3dd69b3c066a6860554a77bf'
 'b8b61059626efa996a60be9bb9320e10' '28bbae6599b09d39ca406b747b6632b1']
  payment_type: ['credit_card' 'boleto' 'voucher' 'debit_card' 'not_defined']

order_reviews:
  review_id: ['7bc2406110b926393aa56f80a40eba40' '80e641a11e56f04c1ad469d5645fdfde'
 '228ce5500dc1d8e020d8d1322874b6f0' ... 'b3de70c89b1510c4cd3d0649fd302472'
 '1adeb9d84d72fe4e337617733eb85149' 'efe49f1d6f951dd88b51e6ccd4cc548f']
  order_id: ['73fc7af87114b39712e6da79b0a377eb' 'a548910a1c6147796b98fdf73dbeba33'
 'f9e4b658b201a9f2ecdecbb34bed034b' ... '55d4004744368f5571d1f590031933e4'
 '7725825d039fc1f0ceb7635e3f7d9206' '90531360ecb1eec2a1fbb265a0db0508']

products:
  product_id: ['1e9e8ef04dbcff4541ed26657ea517e5' '3aa071139cb16b67ca9e5dea641aaa2f'
 '96bd76ec8810374ed1b65e291975717f' ... '9a7c6041fa9592d9d9ef6cfe62a71f8c'
 '83808703fc0706a22e264b9d75f04a2e' '106392145fca363410d287a815be6de4']
  product_category_name: ['perfumaria' 'artes' 'esporte_lazer' 'bebes' 'utilidades_domesticas'
 'instrumentos_musicais' 'cool_stuff' 'moveis_decoracao'
 'eletrodomesticos' 'brinquedos' 'cama_mesa_banho'
 'construcao_ferramentas_seguranca' 'informatica_acessorios'
 'beleza_saude' 'malas_acessorios' 'ferramentas_jardim'
 'moveis_escritorio' 'automotivo' 'eletronicos' 'fashion_calcados'
 'telefonia' 'papelaria' 'fashion_bolsas_e_acessorios' 'pcs'
 'casa_construcao' 'relogios_presentes'
 'construcao_ferramentas_construcao' 'pet_shop' 'eletroportateis'
 'agro_industria_e_comercio' 'moveis_sala' 'sinalizacao_e_seguranca'
 'climatizacao' 'consoles_games' 'livros_interesse_geral'
 'construcao_ferramentas_ferramentas' 'fashion_underwear_e_moda_praia'
 'fashion_roupa_masculina'
 'moveis_cozinha_area_de_servico_jantar_e_jardim'
 'industria_comercio_e_negocios' 'telefonia_fixa'
 'construcao_ferramentas_iluminacao' 'livros_tecnicos'
 'eletrodomesticos_2' 'artigos_de_festas' 'bebidas' 'market_place'
 'la_cuisine' 'construcao_ferramentas_jardim' 'fashion_roupa_feminina'
 'casa_conforto' 'audio' 'alimentos_bebidas' 'musica' 'alimentos'
 'tablets_impressao_imagem' 'livros_importados'
 'portateis_casa_forno_e_cafe' 'fashion_esporte' 'artigos_de_natal'
 'fashion_roupa_infanto_juvenil' 'dvds_blu_ray' 'artes_e_artesanato'
 'pc_gamer' 'moveis_quarto' 'cine_foto' 'fraldas_higiene' 'flores'
 'casa_conforto_2' 'portateis_cozinha_e_preparadores_de_alimentos'
 'seguros_e_servicos' 'moveis_colchao_e_estofado' 'cds_dvds_musicais']

customers:
  customer_id: ['06b8999e2fba1a1fbc88172c00ba8bc7' '18955e83d337fd6b2def6b18a428ac77'
 '4e7b3e00288586ebd08712fdd0374a03' ... '5e28dfe12db7fb50a4b2f691faecea5e'
 '56b18e2166679b8a959d72dd06da27f9' '274fa6071e5e17fe303b9748641082c8']
  customer_unique_id: ['861eff4711a542e4b93843c6dd7febb0' '290c77bc529b7ac935b93aa66c333dc3'
 '060e732b5b29e8181a18229c7b0b2b5e' ... 'e9f50caf99f032f0bf3c55141f019d99'
 '73c2643a0a458b49f58cea58833b192e' '84732c5050c01db9b23e19ba39899398']
  customer_city: ['franca' 'sao bernardo do campo' 'sao paulo' ... 'monte bonito'
 'sao rafael' 'eugenio de castro']
  customer_state: ['SP' 'SC' 'MG' 'PR' 'RJ' 'RS' 'PA' 'GO' 'ES' 'BA' 'MA' 'MS' 'CE' 'DF'
 'RN' 'PE' 'MT' 'AM' 'AP' 'AL' 'RO' 'PB' 'TO' 'PI' 'AC' 'SE' 'RR']

sellers:
  seller_id: ['3442f8959a84dea7ee197c632cb2df15' 'd1b65fc7debc3361ea86b5f14c68d2e2'
 'ce3ad9de960102d0677a81f5d0bb7b2d' ... '74871d19219c7d518d0090283e03c137'
 'e603cf3fec55f8697c9059638d6c8eb5' '9e25199f6ef7e7c347120ff175652c3b']
  seller_city: ['campinas' 'mogi guacu' 'rio de janeiro' 'sao paulo' 'braganca paulista'
 'brejao' 'penapolis' 'curitiba' 'anapolis' 'itirapina' 'tubarao'
 'lauro de freitas' 'imbituba' 'brasilia' 'porto seguro' 'guaruja'
 'tabatinga' 'salto' 'tres de maio' 'belo horizonte' 'arapongas'
 'sao bernardo do campo' 'tatui' 'garopaba' 'camanducaia' 'tupa'
 'guarulhos' 'sao jose dos pinhais' 'sao ludgero' 'sao jose' 'piracicaba'
 'porto alegre' 'congonhal' 'santo andre' 'osasco' 'valinhos' 'joinville'
 'saquarema' 'barra velha' 'petropolis' 'santo antonio da patrulha'
 'ponta grossa' 'santana de parnaiba' 'sao carlos' 'ibitinga' 'barueri'
 'caxias do sul' 'araguari' 'contagem' 'jaragua do sul' 'lages - sc'
 'bento goncalves' 'catanduva' 'ribeirao pires' 'jaboticabal' 'echapora'
 'cotia' 'rio do sul' 'sorocaba' 'pradopolis' 'itaborai' 'mirassol'
 'birigui' 'assis' 'jaguariuna' 'araraquara' 'macae' 'rio claro'
 'londrina' 'ribeirao preto' 'tres coracoes' 'nhandeara' 'orleans'
 'cuiaba' 'formosa do oeste' 'santos' 'santa terezinha de goias'
 'arvorezinha' 'guiricema' 'caruaru' 'franca' 'salvador' 'diadema'
 'itaquaquecetuba' 'lencois paulista' 'carapicuiba' 'uruacu' 'itajai'
 'loanda' 'maringa' 'ferraz de vasconcelos' 'limeira' 'claudio' 'niteroi'
 'osvaldo cruz' 'sao goncalo' 'jaciara' 'balenario camboriu' 'timbo'
 'jacutinga' 'fortaleza' 'ferraz de  vasconcelos' 'mirandopolis' 'bauru'
 'jacarei' 'itu' 'laranjeiras do sul' 'videira' 'florianopolis'
 'itapecerica da serra' 'mamanguape' 'ponte nova' 'goioere' 'pederneiras'
 'itapevi' 'goiania' 'campina grande' 'estancia velha' 'resende' 'maua'
 'caratinga' 'auriflama/sp' 'cafelandia' 'uba' 'sao paulo / sao paulo'
 'sao jose do rio preto' 'porto ferreira' 'tres coroas' 'blumenau'
 'mogi das cruzes' 'jaci' 'laranjal paulista' 'americana' 'sertanopolis'
 'apucarana' 'colombo' 'vicente de carvalho' 'mesquita' 'sao pauo'
 'cascavel' 'fazenda rio grande' 'taboao da serra' 'sao jose dos campos'
 'toledo' 'marechal candido rondon' 'jundiai' 'mandirituba' 'suzano'
 'vespasiano' 'santa rosa' 'sao joaquim da barra' 'santo antonio de posse'
 'uruguaiana' 'campanha' 'piracanjuba' 'concordia' 'santa rita do sapucai'
 'barretos' 'indaiatuba' 'nilopolis' 'pompeia' 'barro alto' 'são paulo'
 'praia grande' 'luiz alves' 'brusque' 'criciuma' 'jales' 'atibaia'
 'rio branco' 'barra mansa' 'marilia' 'bahia' 'taubate' 'cascavael'
 'monteiro lobato' 'viana' 'paraiba do sul' 'mococa' 'sao roque' 'passos'
 'francisco beltrao' 'tocantins' 'porto belo' 'nova iguacu' 'icara'
 'lajeado' 'horizontina' 'votorantim' 'campo bom' 'monte alto'
 'fernandopolis' 'pedreira' 'poa' 'divinopolis' 'santa barbara d´oeste'
 'canoas' 'mombuca' 'sete lagoas' 'campo do meio' 'cordeiropolis'
 'uberlandia' 'santa barbara d oeste' 'volta redonda' '04482255'
 'aracatuba' 'monte siao' 'garuva' 'bonfinopolis de minas' 'cosmopolis'
 'pocos de caldas' 'artur nogueira' 'joao pessoa' 'dois corregos'
 'araquari' 'novo hamburgo, rio grande do sul, brasil' 'floranopolis'
 'sumare' 'guaira' 'cachoeiro de itapemirim' 'serrana' 'rolandia'
 'congonhas' 'sao  jose dos pinhais' 'boituva' 'mairipora' 'guaimbe'
 'parai' 'aperibe' 'jaguaruna' 'vila velha' 'juiz de fora' 'fronteira'
 'novo horizonte' 'pilar do sul' 'itajobi' 'cariacica / es' 'prados'
 'mucambo' 'montes claros' 'vicosa' 'porto velho' 'sao jose do rio pardo'
 'pato branco' 'sao joao del rei' 'presidente prudente' 'paracambi'
 'serra negra' 'sao caetano do sul' 'bom jardim' 'serra redonda'
 'sao francisco do sul' 'betim' 'imbituva' 'guaratuba' 'teresina'
 "sao miguel d'oeste" 'california' 'japira' 'foz do iguacu'
 'nova friburgo' 'itau de minas' 'oliveira' 'sabara' 'pedrinhas paulista'
 'votuporanga' 'holambra' 'ararangua' 'pinhais' 'pato bragado' 'carazinho'
 'arinos' 'sao pedro' 'lages' 'ampere' 'itauna' 'mogi mirim' 'curitibanos'
 'brasilia df' 'mogi das cruses' 'hortolandia' 'ipatinga' 'laguna'
 'dores de campos' 'sao paulo - sp' 'araras' 'divisa nova'
 'igaracu do tiete' 'pitangueiras' 'campo grande' 'garca'
 'presidente epitacio' 'sbc/sp' "arraial d'ajuda (porto seguro)"
 'pacatuba' 'formosa' 'borda da mata' 'ubatuba' 'entre rios do oeste'
 'formiga' 'venancio aires' 'navegantes' 'cruzeiro' 'santa maria' 'muriae'
 'santo andre/sao paulo' 'ipe' 'messias targino' 'varginha' 'botucatu'
 'domingos martins' 'uberaba' 'coronel fabriciano' 'cachoeirinha'
 's jose do rio preto' 'taruma' 'pirassununga' 'aruja' 'sp / sp'
 'angra dos reis' 'juzeiro do norte' 'laurentino' 'flores da cunha'
 'montenegro' 'pedregulho' 'novo hamburgo' 'torres' 'aracaju'
 'santa catarina' 'joao pinheiro' 'bady bassitt' 'sinop' 'guarapuava'
 'araucaria' 'vitoria' 'batatais' 'lagoa santa' 'chapeco' 'umuarama'
 'belford roxo' 'cariacica' 'monte alegre do sul' 'sp' 'lagoa da prata'
 'rolante' 'teresopolis' 'itaporanga' 'campo largo' 'sao joao de meriti'
 'maua/sao paulo' 'bom jesus dos perdoes' 'brotas' 'irece' 'coxim' 'jau'
 'conselheiro lafaiete' 'amparo' 'sao miguel do oeste' 'gaspar'
 'rio bonito' 'mandaguari' 'vargem grande paulista' 'conchal' 'cambe'
 'marialva' 'alfenas' 'balneario camboriu' 'palhoca'
 'sao bernardo do capo' 'guara' 'colatina' 'franco da rocha' 'lambari'
 'mogi das cruzes / sp' 'treze tilias' 'rio de janeiro \\rio de janeiro'
 'paulo lopes' 'santa cecilia' 'braco do norte' 'floresta' 'farroupilha'
 'castro' 'luziania' 'joao monlevade' 'pelotas' 'sao bento'
 'campos dos goytacazes' 'ouro fino' 'sao jose dos pinhas' 'tiete'
 'viamao' 'janauba' 'capivari' 'santa terezinha de itaipu' 'igrejinha'
 'sao bento do sul' 'duque de caxias' 'araxa' 'canoinhas' 'recife'
 'barbacena/ minas gerais' 'vera cruz' 'parnamirim' 'santo angelo'
 'paincandu' 'tres rios' 'tanabi' 'portoferreira' 'itatiba' 'sarandi'
 'cravinhos' 'morrinhos' 'bebedouro' 'almirante tamandare' 'bertioga'
 'natal' 'belo horizont' 'ivoti' 'andira-pr' 'cerqueira cesar' 'marapoama'
 'imigrante' 'mairinque' 'sao paulo sp' 'rio de janeiro / rio de janeiro'
 'andradas' 'sando andre' 'nova odessa' 'paulinia' 'extrema' 'olimpia'
 'angra dos reis rj' 'ronda alta' 'sao  paulo' 'sao vicente' 'pinhais/pr'
 'portao' 'registro' 'ao bernardo do campo' 'carmo do cajuru'
 'embu das artes' 'fernando prestes' 'castro pires' 'vargem grande do sul'
 'campina das missoes' 'sao pedro da aldeia' 'miguelopolis' 'itapui' 'sbc'
 'neopolis' 'mineiros do tiete' 'varzea paulista' 'nova lima' 'barbacena'
 'caieiras' 'buritama' 'erechim' 'itapetininga' 'pinhalzinho' 'descalvado'
 'pitanga' 'bage' 'taio' "santa barbara d'oeste" 'patos de minas'
 'garulhos' 'jarinu' 'nova petropolis' 'ribeirao preto / sao paulo'
 'camboriu' 'nova trento' 'sao luis' 'sao jose do rio pret' 'eusebio'
 'itaipulandia' 'ipira' 'campo magro' 'tiradentes' 'sao paluo' 'baependi'
 'embu guacu' 'paraiso do sul' 'aparecida' 'cataguases' 'bariri'
 'abadia de goias' 'alambari' 'ji parana' 'vassouras' 'lorena' 'rodeio'
 'louveira' 'guanhaes' 'santo antonio de padua' 'presidente getulio'
 'campos novos' 'eunapolis' 'engenheiro coelho' 'rio das pedras'
 'afonso claudio' 'carapicuiba / sao paulo' 'centro' 'parana' 'indaial'
 'bombinhas' 'orlandia' 'itapeva' 'sao sebastiao' 'macatuba'
 'sao joao da boa vista' 'teixeira soares' 'mandaguacu' 'rio do oeste'
 'vendas@creditparts.com.br' 'armacao dos buzios' 'mateus leme'
 'sao paulop' 'campo limpo paulista' 'socorro' 'serra' 'bocaiuva do sul'
 'ilheus' 'imbe' 'soledade' 'cajamar' 'rio negrinho' 'clementina'
 'francisco morato' 'rio grande' 'xaxim' 'manaus' 'terra boa'
 'minas gerais' 'avare' 'ibirite' 'santa maria da serra' 'auriflama'
 'condor' 'ibia' 'guanambi' 'caucaia' 'cordilheira alta' 'carmo da mata'
 'ouro preto' 'pedro leopoldo' 'santa rosa de viterbo' 'xanxere'
 'alvares machado' 'scao jose do rio pardo' 'ribeirao das neves'
 'medianeira' 'massaranduba' 'cornelio procopio' 'pirituba' 'jambeiro'
 'sao leopoldo' 'aguas claras df' 'ribeirao pretp' 'cianorte'
 'feira de santana' 'cachoeira do sul' 'guariba'
 'sao sebastiao da grama/sp' 'dracena' 'ourinhos' 'robeirao preto'
 'cacador' 'gama' 'queimados' 'cananeia' 'presidente bernardes' 'pinhalao'
 'sombrio' 'campo mourao' 'ilicinea' 'itabira' 'barrinha' 'jussara'
 'uniao da vitoria' 'triunfo' 'santa cruz do sul' 'colorado' 'itapema'
 'sapiranga' 'paranavai' 'alvorada' 'ipaussu' 'rio verde' 'mage'
 'tabao da serra' 'bofete' 'picarras' 'marica' 'jaragua'
 'governador valadares' 'rio de janeiro, rio de janeiro, brasil'
 'pouso alegre' 'timoteo' 'muqui' 'ipua' 'jacarei / sao paulo'
 'varzea alegre' 'guaratingueta' 'tambau' 'irati' 'riberao preto'
 'aparecida de goiania' 'bandeirantes' 'vitoria de santo antao' 'palotina'
 'leme']
  seller_state: ['SP' 'RJ' 'PE' 'PR' 'GO' 'SC' 'BA' 'DF' 'RS' 'MG' 'RN' 'MT' 'CE' 'PB'
 'AC' 'ES' 'RO' 'PI' 'MS' 'SE' 'MA' 'AM' 'PA']

category_translation:
  product_category_name: ['beleza_saude' 'informatica_acessorios' 'automotivo' 'cama_mesa_banho'
 'moveis_decoracao' 'esporte_lazer' 'perfumaria' 'utilidades_domesticas'
 'telefonia' 'relogios_presentes' 'alimentos_bebidas' 'bebes' 'papelaria'
 'tablets_impressao_imagem' 'brinquedos' 'telefonia_fixa'
 'ferramentas_jardim' 'fashion_bolsas_e_acessorios' 'eletroportateis'
 'consoles_games' 'audio' 'fashion_calcados' 'cool_stuff'
 'malas_acessorios' 'climatizacao' 'construcao_ferramentas_construcao'
 'moveis_cozinha_area_de_servico_jantar_e_jardim'
 'construcao_ferramentas_jardim' 'fashion_roupa_masculina' 'pet_shop'
 'moveis_escritorio' 'market_place' 'eletronicos' 'eletrodomesticos'
 'artigos_de_festas' 'casa_conforto' 'construcao_ferramentas_ferramentas'
 'agro_industria_e_comercio' 'moveis_colchao_e_estofado' 'livros_tecnicos'
 'casa_construcao' 'instrumentos_musicais' 'moveis_sala'
 'construcao_ferramentas_iluminacao' 'industria_comercio_e_negocios'
 'alimentos' 'artes' 'moveis_quarto' 'livros_interesse_geral'
 'construcao_ferramentas_seguranca' 'fashion_underwear_e_moda_praia'
 'fashion_esporte' 'sinalizacao_e_seguranca' 'pcs' 'artigos_de_natal'
 'fashion_roupa_feminina' 'eletrodomesticos_2' 'livros_importados'
 'bebidas' 'cine_foto' 'la_cuisine' 'musica' 'casa_conforto_2'
 'portateis_casa_forno_e_cafe' 'cds_dvds_musicais' 'dvds_blu_ray' 'flores'
 'artes_e_artesanato' 'fraldas_higiene' 'fashion_roupa_infanto_juvenil'
 'seguros_e_servicos']
  product_category_name_english: ['health_beauty' 'computers_accessories' 'auto' 'bed_bath_table'
 'furniture_decor' 'sports_leisure' 'perfumery' 'housewares' 'telephony'
 'watches_gifts' 'food_drink' 'baby' 'stationery' 'tablets_printing_image'
 'toys' 'fixed_telephony' 'garden_tools' 'fashion_bags_accessories'
 'small_appliances' 'consoles_games' 'audio' 'fashion_shoes' 'cool_stuff'
 'luggage_accessories' 'air_conditioning'
 'construction_tools_construction'
 'kitchen_dining_laundry_garden_furniture' 'costruction_tools_garden'
 'fashion_male_clothing' 'pet_shop' 'office_furniture' 'market_place'
 'electronics' 'home_appliances' 'party_supplies' 'home_confort'
 'costruction_tools_tools' 'agro_industry_and_commerce'
 'furniture_mattress_and_upholstery' 'books_technical' 'home_construction'
 'musical_instruments' 'furniture_living_room' 'construction_tools_lights'
 'industry_commerce_and_business' 'food' 'art' 'furniture_bedroom'
 'books_general_interest' 'construction_tools_safety'
 'fashion_underwear_beach' 'fashion_sport' 'signaling_and_security'
 'computers' 'christmas_supplies' 'fashio_female_clothing'
 'home_appliances_2' 'books_imported' 'drinks' 'cine_photo' 'la_cuisine'
 'music' 'home_comfort_2' 'small_appliances_home_oven_and_coffee'
 'cds_dvds_musicals' 'dvds_blu_ray' 'flowers' 'arts_and_craftmanship'
 'diapers_and_hygiene' 'fashion_childrens_clothes' 'security_and_services']

In [116]:
# Fix typos
products = products.rename(columns={
    "product_name_lenght": "product_name_length",
    "product_description_lenght": "product_description_length"
})

In [117]:
# Correct category translation column
category_translation = category_translation.rename(
    columns={"ï»¿product_category_name": "product_category_name"}
)

In [118]:
# Keep review_score between 1 and 5
order_reviews = order_reviews[order_reviews['review_score'].between(1, 5)]

## **7. Join Validation**

In [119]:
# CHECK FOREIGN KEYS – OLIST E-COMMERCE

# 1. ORDERS → CUSTOMERS
print("\n=== FOREIGN KEY CHECK: ORDERS → CUSTOMERS ===")
invalid_orders_customers = (~orders["customer_id"].isin(customers["customer_id"])).sum()
print(f"Orders with invalid customer_id references: {invalid_orders_customers}")

# 2. ORDER ITEMS → ORDERS
print("\n=== FOREIGN KEY CHECK: ORDER ITEMS → ORDERS ===")
invalid_orderitems_orders = (~order_items["order_id"].isin(orders["order_id"])).sum()
print(f"Order items with invalid order_id references: {invalid_orderitems_orders}")

# 3. ORDER ITEMS → PRODUCTS
print("\n=== FOREIGN KEY CHECK: ORDER ITEMS → PRODUCTS ===")
invalid_orderitems_products = (~order_items["product_id"].isin(products["product_id"])).sum()
print(f"Order items with invalid product_id references: {invalid_orderitems_products}")

# 4. ORDER ITEMS → SELLERS
print("\n=== FOREIGN KEY CHECK: ORDER ITEMS → SELLERS ===")
invalid_orderitems_sellers = (~order_items["seller_id"].isin(sellers["seller_id"])).sum()
print(f"Order items with invalid seller_id references: {invalid_orderitems_sellers}")

# 5. ORDER PAYMENTS → ORDERS
print("\n=== FOREIGN KEY CHECK: ORDER PAYMENTS → ORDERS ===")
invalid_payments_orders = (~order_payments["order_id"].isin(orders["order_id"])).sum()
print(f"Payments with invalid order_id references: {invalid_payments_orders}")

# 6. ORDER REVIEWS → ORDERS
print("\n=== FOREIGN KEY CHECK: ORDER REVIEWS → ORDERS ===")
invalid_reviews_orders = (~order_reviews["order_id"].isin(orders["order_id"])).sum()
print(f"Reviews with invalid order_id references: {invalid_reviews_orders}")

=== FOREIGN KEY CHECK: ORDERS → CUSTOMERS ===
Orders with invalid customer_id references: 0

=== FOREIGN KEY CHECK: ORDER ITEMS → ORDERS ===
Order items with invalid order_id references: 52331

=== FOREIGN KEY CHECK: ORDER ITEMS → PRODUCTS ===
Order items with invalid product_id references: 1604

=== FOREIGN KEY CHECK: ORDER ITEMS → SELLERS ===
Order items with invalid seller_id references: 0

=== FOREIGN KEY CHECK: ORDER PAYMENTS → ORDERS ===
Payments with invalid order_id references: 49143

=== FOREIGN KEY CHECK: ORDER REVIEWS → ORDERS ===
Reviews with invalid order_id references: 46551

In [120]:
# HANDLING ORPHAN VALUE

orders = orders.dropna(subset=[
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]).copy()

# Keep only rows that reference valid orders
valid_order_ids = orders["order_id"]
order_items = order_items[order_items["order_id"].isin(valid_order_ids)].copy()
order_payments = order_payments[order_payments["order_id"].isin(valid_order_ids)].copy()
order_reviews = order_reviews[order_reviews["order_id"].isin(valid_order_ids)].copy()

# Keep only order_items that reference existing products
order_items = order_items[order_items["product_id"].isin(products["product_id"])].copy()

In [121]:
# RE-CHECK HANDLED ORPHAN VALUES

# 1. ORDERS → CUSTOMERS
print("\n=== FOREIGN KEY CHECK: ORDERS → CUSTOMERS ===")
invalid_orders_customers = (~orders["customer_id"].isin(customers["customer_id"])).sum()
print(f"Orders with invalid customer_id references: {invalid_orders_customers}")

# 2. ORDER ITEMS → ORDERS
print("\n=== FOREIGN KEY CHECK: ORDER ITEMS → ORDERS ===")
invalid_orderitems_orders = (~order_items["order_id"].isin(orders["order_id"])).sum()
print(f"Order items with invalid order_id references: {invalid_orderitems_orders}")

# 3. ORDER ITEMS → PRODUCTS
print("\n=== FOREIGN KEY CHECK: ORDER ITEMS → PRODUCTS ===")
invalid_orderitems_products = (~order_items["product_id"].isin(products["product_id"])).sum()
print(f"Order items with invalid product_id references: {invalid_orderitems_products}")

# 4. ORDER ITEMS → SELLERS
print("\n=== FOREIGN KEY CHECK: ORDER ITEMS → SELLERS ===")
invalid_orderitems_sellers = (~order_items["seller_id"].isin(sellers["seller_id"])).sum()
print(f"Order items with invalid seller_id references: {invalid_orderitems_sellers}")

# 5. ORDER PAYMENTS → ORDERS
print("\n=== FOREIGN KEY CHECK: ORDER PAYMENTS → ORDERS ===")
invalid_payments_orders = (~order_payments["order_id"].isin(orders["order_id"])).sum()
print(f"Payments with invalid order_id references: {invalid_payments_orders}")

# 6. ORDER REVIEWS → ORDERS
print("\n=== FOREIGN KEY CHECK: ORDER REVIEWS → ORDERS ===")
invalid_reviews_orders = (~order_reviews["order_id"].isin(orders["order_id"])).sum()
print(f"Reviews with invalid order_id references: {invalid_reviews_orders}")

=== FOREIGN KEY CHECK: ORDERS → CUSTOMERS ===
Orders with invalid customer_id references: 0

=== FOREIGN KEY CHECK: ORDER ITEMS → ORDERS ===
Order items with invalid order_id references: 0

=== FOREIGN KEY CHECK: ORDER ITEMS → PRODUCTS ===
Order items with invalid product_id references: 0

=== FOREIGN KEY CHECK: ORDER ITEMS → SELLERS ===
Order items with invalid seller_id references: 0

=== FOREIGN KEY CHECK: ORDER PAYMENTS → ORDERS ===
Payments with invalid order_id references: 0

=== FOREIGN KEY CHECK: ORDER REVIEWS → ORDERS ===
Reviews with invalid order_id references: 0

## **8. Final Data Inspection**

In [122]:
# FINAL DATA INSPECTION

datasets = {
    "orders": orders,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "products": products,
    "customers": customers,
    "sellers": sellers,
    "category_translation": category_translation
}

for name, df in datasets.items():
    print(f"\n{'='*40}")
    print(f"{name} Table")
    print(f"{'='*40}")
    print("Shape:", df.shape)
    print("\nInfo:")
    df.info()
    print("\nPreview:")
    display(df.head())

========================================
orders Table
========================================
Shape: (52778, 8)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52778 entries, 0 to 52777
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       52778 non-null  object
 1   customer_id                    52778 non-null  object
 2   order_status                   52778 non-null  object
 3   order_purchase_timestamp       52778 non-null  datetime64[ns]
 4   order_approved_at              52778 non-null  datetime64[ns]
 5   order_delivered_carrier_date   52778 non-null  datetime64[ns]
 6   order_delivered_customer_date  52778 non-null  datetime64[ns]
 7   order_estimated_delivery_date  52778 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 3.2+ MB

Preview:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
1,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
2,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
3,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18
4,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08

========================================
order_items Table
========================================
Shape: (59659, 7)

Info:
<class 'pandas.core.frame.DataFrame'>
Index: 59659 entries, 2 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             59659 non-null  object
 1   order_item_id        59659 non-null  int64
 2   product_id           59659 non-null  object
 3   seller_id            59659 non-null  object
 4   shipping_limit_date  59659 non-null  datetime64[ns]
 5   price                59659 non-null  float64
 6   freight_value        59659 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 3.6+ MB

Preview:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40

========================================
order_payments Table
========================================
Shape: (54743, 5)

Info:
<class 'pandas.core.frame.DataFrame'>
Index: 54743 entries, 0 to 103884
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              54743 non-null  object
 1   payment_sequential    54743 non-null  int64
 2   payment_type          54743 non-null  object
 3   payment_installments  54743 non-null  int64
 4   payment_value         54743 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 2.5+ MB

Preview:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
5,298fcdf1f73eb413e4d26d01b25bc1cd,1,credit_card,2,96.12
8,1f78449c87a54faf9e96e88ba1491fa9,1,credit_card,6,341.09

========================================
order_reviews Table
========================================
Shape: (52673, 5)

Info:
<class 'pandas.core.frame.DataFrame'>
Index: 52673 entries, 0 to 99222
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                52673 non-null  object
 1   order_id                 52673 non-null  object
 2   review_score             52673 non-null  int64
 3   review_creation_date     52673 non-null  datetime64[ns]
 4   review_answer_timestamp  52673 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 2.4+ MB

Preview:

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,2018-02-17,2018-02-18 14:36:24
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,2018-03-01,2018-03-02 10:26:53
5,15197aa66ff4d0650b5434f1b46cda19,b18dcdf73be66366873cd26c5724d1dc,1,2018-04-13,2018-04-16 00:39:37

========================================
products Table
========================================
Shape: (32340, 9)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32340 entries, 0 to 32339
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32340 non-null  object
 1   product_category_name       32340 non-null  object
 2   product_name_length         32340 non-null  float64
 3   product_description_length  32340 non-null  float64
 4   product_photos_qty          32340 non-null  float64
 5   product_weight_g            32340 non-null  float64
 6   product_length_cm           32340 non-null  float64
 7   product_height_cm           32340 non-null  float64
 8   product_width_cm            32340 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.2+ MB

Preview:

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

========================================
customers Table
========================================
Shape: (99441, 5)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

Preview:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

========================================
sellers Table
========================================
Shape: (3095, 4)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

Preview:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

========================================
category_translation Table
========================================
Shape: (71, 2)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

Preview:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

## **9. Save Cleaned Data**

In [ ]:
orders.to_csv("orders.csv", index=False)
order_items.to_csv("order_items.csv", index=False)
order_payments.to_csv("order_payments.csv", index=False)
order_reviews.to_csv("order_reviews.csv", index=False)
products.to_csv("products.csv", index=False)
customers.to_csv("customers.csv", index=False)
sellers.to_csv("sellers.csv", index=False)
category_translation.to_csv("category_translation.csv", index=False)